@DaanSelen Docker overhaul intermediate commit.

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,28 +1,15 @@
 ### STAGE 1 BUILDING.
 FROM node:lts-alpine AS builder
 
+# Any value inside one of the disable ARGs will be accepted.
 ARG DISABLE_MINIFY=""
 ARG DISABLE_TRANSLATE="yes"
 
 RUN mkdir -p /opt/meshcentral/meshcentral
+WORKDIR /opt/meshcentral
 COPY ./ /opt/meshcentral/meshcentral/
 
-# Check if minify should be disabled on compilation.
-RUN if ! [ -z "$DISABLE_MINIFY" ] \
-    && [ "$DISABLE_MINIFY" != "yes" ] && [ "$DISABLE_MINIFY" != "YES" ] \
-    && [ "$DISABLE_MINIFY" != "true" ] && [ "$DISABLE_MINIFY" != "TRUE" ]; then \
-        echo "Invalid value for build argument DISABLE_MINIFY, possible values: 'yes' or 'true'"; \
-        exit 1; \
-    fi
-# Check if translations should be compiled.
-RUN if ! [ -z "$DISABLE_TRANSLATE" ] \
-    && [ "$DISABLE_TRANSLATE" != "yes" ] && [ "$DISABLE_TRANSLATE" != "YES" ] \
-    && [ "$DISABLE_TRANSLATE" != "true" ] && [ "$DISABLE_TRANSLATE" != "TRUE" ]; then \
-        echo "Invalid value for build argument DISABLE_TRANSLATE, possible values: 'yes' or 'true'"; \
-        exit 1; \
-    fi
-
-# Check the Docker build arguments and execute them accordingly.
+# Check the Docker build arguments and if they are empty do the task.
 RUN if [ -z "$DISABLE_MINIFY" ] || [ -z "$DISABLE_TRANSLATE" ]; then \
         cd meshcentral && \
         npm install html-minifier@4.0.0 jsdom@26.0.0 esprima@4.0.1 && \
@@ -40,8 +27,7 @@ RUN if [ -z "$DISABLE_MINIFY" ] || [ -z "$DISABLE_TRANSLATE" ]; then \
     fi
 # Possible more updated alternative? @minify-html/node@0.15.0 -> https://www.npmjs.com/package/@minify-html/node
 
-# cleanup
-RUN ls -l /opt/meshcentral/meshcentral
+# cleanup for inter-container copying.
 RUN rm -rf /opt/meshcentral/meshcentral/docker
 RUN rm -rf /opt/meshcentral/meshcentral/node_modules
 
@@ -49,70 +35,139 @@ RUN rm -rf /opt/meshcentral/meshcentral/node_modules
 
 FROM alpine:latest
 
-ARG INCLUDE_MONGODBTOOLS=""
 ARG PREINSTALL_LIBS="false"
 
 # environment variables
 ENV NODE_ENV="production"
-ENV CONFIG_FILE="config.json"
+ENV CONFIG_FILE="/opt/meshcentral/meshcentral-data/config.json"
+ENV DYNAMIC_CONFIG="true"
 
-# environment variables for initial configuration file
-ENV USE_MONGODB="false"
-ENV MONGO_INITDB_ROOT_USERNAME="root"
-ENV MONGO_INITDB_ROOT_PASSWORD="pass"
-ENV MONGO_URL=""
-ENV HOSTNAME="localhost"
-ENV ALLOW_NEW_ACCOUNTS="true"
+# environment variables for the above defined MeshCentral Config.json
 ENV ALLOWPLUGINS="false"
-ENV LOCALSESSIONRECORDING="true"
-ENV MINIFY="false"
-ENV WEBRTC="false"
-ENV IFRAME="false"
-ENV REVERSE_PROXY="false"
-ENV REVERSE_PROXY_TLS_PORT=""
-ENV ARGS=""
+ENV ALLOW_NEW_ACCOUNTS="false"
 ENV ALLOWED_ORIGIN="false"
+ENV ARGS=""
+ENV HOSTNAME="localhost"
+ENV IFRAME="false"
+ENV LOCALSESSIONRECORDING="true"
+ENV MINIFY="true"
+ENV REGENSESSIONKEY="false"
+ENV REVERSE_PROXY=""
+ENV REVERSE_PROXY_TLS_PORT=""
+ENV WEBRTC="false"
+
+
+# MongoDB Variables
+ARG INCLUDE_MONGODB_TOOLS="false"
+
+ENV USE_MONGODB="false"
+ENV MONGO_HOST=""
+ENV MONGO_PORT="27017"
+ENV MONGO_USERNAME=""
+ENV MONGO_PASS=""
+# The following Mongo variable overwrites most previously declared variables.
+ENV MONGO_URL=""
+
+# PostgreSQL Variables
+ARG INCLUDE_POSTGRESQL_TOOLS="false"
+
+ENV USE_POSTGRESQL="false"
+ENV PSQL_HOST=""
+ENV PSQL_PORT="5432"
+ENV PSQL_USER=""
+ENV PSQL_PASS=""
+ENV PSQL_DATABASE=""
+
+# MariaDB/MySQL Variables, Alpine Linux only provides the actual MariaDB binaries.
+ARG INCLUDE_MARIADB_TOOLS="false"
+
+ENV USE_MARIADB="false"
+ENV MARIADB_HOST=""
+ENV MARIADB_PORT="3306"
+ENV MARIADB_USER=""
+ENV MARIADB_PASS=""
+ENV MARIADB_DATABASE=""
 
 RUN mkdir -p /opt/meshcentral/meshcentral
-
-# meshcentral installation
 WORKDIR /opt/meshcentral
 
 RUN apk update \
-    && apk add --no-cache --update tzdata nodejs npm bash python3 postgresql-client make gcc g++ \
-    && rm -rf /var/cache/apk/*
+    && apk add --no-cache --update \
+    bash gcc g++ jq make nodejs npm postgresql-client python3 tzdata \
+    && rm -rf /var/cache/* \
+        /tmp/* \
+        /usr/share/man/ \
+        /usr/share/doc/ \
+        /var/log/* \
+        /var/spool/* \
+        /usr/lib/debug/
 RUN npm install -g npm@latest
 
-# NOTE: ALL MODULES MUST HAVE A VERSION NUMBER AND THE VERSION MUST MATCH THAT USED IN meshcentral.js mainStart()
-RUN if ! [ -z "$INCLUDE_MONGODBTOOLS" ] \
-    && [ "$INCLUDE_MONGODBTOOLS" != "yes" ] && [ "$INCLUDE_MONGODBTOOLS" != "YES" ] \
-    && [ "$INCLUDE_MONGODBTOOLS" != "true" ] && [ "$INCLUDE_MONGODBTOOLS" != "TRUE" ]; then \
-        echo -e "\e[0;31;49mInvalid value for build argument INCLUDE_MONGODBTOOLS, possible values: yes/true\e[;0m"; exit 1; \
-    else \
-        apk add --no-cache mongodb-tools; \
-        cd meshcentral && npm install mongodb@6.15.0 saslprep@1.0.3; \
-    fi
+# NOTE: ALL MODULES MUST HAVE A VERSION NUMBER AND THE VERSION MUST MATCH THAT USED IN meshcentraljs mainStart()
+RUN case "$INCLUDE_MONGODB_TOOLS" in \
+        true|yes|TRUE|YES) \
+            apk add --no-cache mongodb-tools && \
+            cd meshcentral && npm install mongodb@6.15.0 saslprep@1.0.3 \
+            ;; \
+        false|no|FALSE|NO) \
+            echo "Not including MongoDB Tools.";; \
+        *) \
+            echo "Invalid value for build argument INCLUDE_MONGODB_TOOLS, possible values: 'yes' or 'true'"; \
+            exit 1;; \
+    esac
+
+RUN case "$INCLUDE_POSTGRESQL_TOOLS" in \
+        true|yes|TRUE|YES) \
+            apk add --no-cache postgresql-client && \
+            cd meshcentral && npm install pg@8.14.1 \
+            ;; \
+        false|no|FALSE|NO) \
+            echo "Not including PostgreSQL Tools.";; \
+        *) \
+            echo -e "Invalid value for build argument INCLUDE_POSTGRESQL_TOOLS, possible values: 'yes' or 'true'"; \
+            exit 1;; \
+    esac
+
+RUN case "$INCLUDE_MARIADB_TOOLS" in \
+        true|yes|TRUE|YES) \
+            apk add --no-cache mariadb-client && \
+            cd meshcentral && npm install mariadb@3.4.0 \
+            ;; \
+        false|no|FALSE|NO) \
+            echo "Not including MariaDB/MySQL Tools.";; \
+        *) \
+            echo -e "Invalid value for build argument INCLUDE_MARIADB_TOOLS, possible values: 'yes' or 'true'"; \
+            exit 1;; \
+    esac
 
 # copy files from builder-image
 COPY --from=builder /opt/meshcentral/meshcentral /opt/meshcentral/meshcentral
-COPY ./docker/entrypoint.sh ./entrypoint.sh
-COPY ./docker/config.json.template /opt/meshcentral/config.json.template
 
 # install dependencies from package.json
 RUN cd meshcentral && npm install
 
-RUN if ! [ -z "$PREINSTALL_LIBS" ] \
-    && [ "$PREINSTALL_LIBS" == "true" ]; then \
-        cd meshcentral && npm install ssh2@1.16.0 semver@7.7.1 nodemailer@6.10.0 image-size@2.0.1 wildleek@2.0.0 otplib@12.0.1 yubikeyotp@0.2.0; \
-    fi
+RUN case "$PREINSTALL_LIBS" in \
+        true|yes|TRUE|YES) \
+            cd meshcentral && \
+            npm install ssh2@1.16.0 semver@7.7.1 nodemailer@6.10.0 image-size@2.0.1 wildleek@2.0.0 otplib@12.0.1 yubikeyotp@0.2.0;; \
+        false|no|FALSE|NO) \
+            echo "Not pre-installing libraries.";; \
+        *) \
+            echo -e "Invalid value for build argument INCLUDE_POSTGRESQL_TOOLS, possible values: 'yes' or 'true'"; \
+            exit 1;; \
+    esac
 
-EXPOSE 80 443 4433
+# Expose only 443 by default to reduce attack surface. (Only encrypted ports).
+EXPOSE 443
 
-# volumes
+# These volumes will be created by default even without any declaration, this allows default persistence in Docker/Podman.
 VOLUME /opt/meshcentral/meshcentral-data
 VOLUME /opt/meshcentral/meshcentral-files
 VOLUME /opt/meshcentral/meshcentral-web
 VOLUME /opt/meshcentral/meshcentral-backups
 
-WORKDIR /opt/meshcentral
+# Copy images from Git repo, place it before ending so recompilation can make good use of cache.
+COPY ./docker/entrypoint.sh ./entrypoint.sh
+COPY ./docker/config.json.template /opt/meshcentral/config.json.template
+
 CMD ["bash", "/opt/meshcentral/entrypoint.sh"]
