chore: rename Dockerfiles

diff --git a/docker/Dockerfile-debian b/docker/Dockerfile-debian
--- a/docker/Dockerfile-debian
+++ b/docker/Dockerfile-debian
@@ -1,7 +1,8 @@
 ### STAGE 1 BUILDING.
-FROM node:lts-alpine3.22 AS builder
+FROM node:22-alpine3.22 AS builder
 
 # Any value inside one of the disable ARGs will be accepted.
+ARG DISABLE_EXTRACT="yes"
 ARG DISABLE_MINIFY="yes"
 ARG DISABLE_TRANSLATE="yes"
 #    NODE_OPTIONS="--max_old_space_size=4096"
@@ -12,13 +13,18 @@ WORKDIR /opt/meshcentral
 COPY ./ /opt/meshcentral/meshcentral/
 
 # Check the Docker build arguments and if they are empty do the task.
-RUN if [ -n "$DISABLE_MINIFY" ] || [ -n "$DISABLE_TRANSLATE" ]; then \
+RUN if [ -n "$DISABLE_EXTRACT" ] || [ -n "$DISABLE_MINIFY" ] || [ -n "$DISABLE_TRANSLATE" ]; then \
         echo -e "----------\nPREPARING ENVIRONMENT...\n----------"; \
         cd meshcentral && \
         npm install html-minifier-terser@7.2.0 jsdom@26.0.0 esprima@4.0.1 && \
         cd translate && \
-        echo -e "----------\nSTARTING THE EXTRACTING PROCESS...\n----------"; \
-        node translate.js extractall && \
+        case "$DISABLE_EXTRACT" in \
+            false|no|FALSE|NO) \
+                echo -e "----------\nSTARTING THE EXTRACTING PROCESS...\n----------"; \
+                node translate.js extractall;; \
+            *) \
+                echo "Setting EXTRACT as disabled.";; \
+        esac && \
         case "$DISABLE_MINIFY" in \
             false|no|FALSE|NO) \
                 echo -e "----------\nSTARTING THE MINIFYING PROCESS...\n----------"; \
@@ -37,14 +43,14 @@ RUN if [ -n "$DISABLE_MINIFY" ] || [ -n "$DISABLE_TRANSLATE" ]; then \
     fi
 # Possible more updated alternative? @minify-html/node@0.15.0 -> https://www.npmjs.com/package/@minify-html/node
 
-RUN rm -rf /opt/meshcentral/meshcentral/docker
-RUN rm -rf /opt/meshcentral/meshcentral/node_modules
+RUN rm -rf /opt/meshcentral/meshcentral/docker /opt/meshcentral/meshcentral/node_modules /opt/meshcentral/meshcentral/docs
 
 ### STAGE 2 PRECOMPILE DEPS MODULE
 
-FROM node:lts-alpine3.22 AS dep-compiler
+FROM node:22-alpine3.22 AS dep-compiler
 
-RUN echo -e "----------\nINSTALLING ALPINE PACKAGES...\n----------"; \
+RUN apk update && \
+    echo -e "----------\nINSTALLING ALPINE PACKAGES...\n----------"; \
     apk add --no-cache --update \
         bash gcc g++ jq make python3 tzdata
 
@@ -56,13 +62,34 @@ RUN jq '.dependencies += {"modern-syslog": "1.2.0", "telegram": "2.26.22"}' pack
     && npm ci --omit=dev \
     && npm cache clean --force
 
-### STAGE 3 BUILDING.
+### STAGE 3 fun. building from source...
 
-FROM alpine:3.22 AS finalizer
+FROM golang:trixie AS mongo-tools-compiler
 
-# copy files from previous layers
-COPY --from=builder /opt/meshcentral/meshcentral /opt/meshcentral/meshcentral
+ARG INCLUDE_MONGODB_TOOLS="false"
+
+FROM node:22-alpine3.22 AS runtime
+
+RUN case "$INCLUDE_MONGODB_TOOLS" in \
+        true|yes|TRUE|YES) \
+            git clone https://github.com/mongodb/mongo-tools /mongo-tools; \
+            cd /mongo-tools; \
+            ./make build -pkgs=mongodump,mongorestore;; \
+        false|no|FALSE|NO) \
+            echo "Not building MongoDB Tools from source, what a shame!"; \
+            mkdir -p /mongo-tools/bin;; \
+        *) \
+            echo "Invalid value for build argument INCLUDE_MONGODB_TOOLS, possible values: 'yes', 'true', 'no' or 'false'"; \
+            exit 1;; \
+    esac
+
+### STAGE 4 BUILDING.
+
+FROM node:lts-trixie-slim AS finalizer
+
+# Copy files from previous layers
 COPY --from=dep-compiler /opt/meshcentral/meshcentral /opt/meshcentral/meshcentral
+COPY --from=mongo-tools-compiler /mongo-tools/bin/ /tmp/bin/
 
 # environment variables
 ENV NODE_ENV="production" \
@@ -118,18 +145,19 @@ ENV MARIADB_HOST="" \
     MARIADB_PASS="" \
     MARIADB_DATABASE=""
 
-RUN mkdir -p /opt/meshcentral/meshcentral
 WORKDIR /opt/meshcentral
 
-RUN echo -e "----------\nINSTALLING ALPINE PACKAGES...\n----------"; \
-    apk add --no-cache --update \
-        bash jq nodejs npm tzdata && \
-    rm -rf /var/cache/* \
-        /tmp/* \
+RUN apt-get update && \
+    echo -e "----------\nINSTALLING DEBIAN PACKAGES...\n----------"; \
+    apt-get install -y --no-install-recommends --no-install-suggests \
+        bash jq tzdata curl && \
+    rm -rf \
+        /var/cache/* \
         /usr/share/man/ \
         /usr/share/doc/ \
         /var/log/* \
         /var/spool/* \
+        /var/tmp/* \
         /usr/lib/debug/ && \
     npm install -g npm@latest
 
@@ -137,7 +165,7 @@ RUN case "$PREINSTALL_LIBS" in \
         true|yes|TRUE|YES) \
             cd meshcentral && \
             echo -e "----------\nPREINSTALLING LIBRARIES...\n----------"; \
-            npm install ssh2@1.16.0 nodemailer@6.10.1 image-size@2.0.2 wildleek@2.0.0 otplib@12.0.1 yubikeyotp@0.2.0;; \
+            npm install ssh2@1.16.0 nodemailer@6.10.1 image-size@2.0.2 wildleek@2.0.0 otplib@12.0.1 yub@0.11.1;; \
         false|no|FALSE|NO) \
             echo "Not pre-installing libraries.";; \
         *) \
@@ -148,10 +176,10 @@ RUN case "$PREINSTALL_LIBS" in \
 # NOTE: ALL MODULES MUST HAVE A VERSION NUMBER AND THE VERSION MUST MATCH THAT USED IN meshcentraljs mainStart()
 RUN case "$INCLUDE_MONGODB_TOOLS" in \
         true|yes|TRUE|YES) \
-            apk add --no-cache mongodb-tools && \
+            mv /tmp/bin/* /usr/bin; \
             cd meshcentral && \
             echo -e "----------\nPREINSTALLING MONGODB LIBRARIES...\n----------"; \
-            npm install mongodb@4.17.2;; \
+            npm install mongodb@4.17.2 @mongodb-js/saslprep@1.3.1;; \
         false|no|FALSE|NO) \
             echo "Not including MongoDB Tools.";; \
         *) \
@@ -161,7 +189,7 @@ RUN case "$INCLUDE_MONGODB_TOOLS" in \
 
 RUN case "$INCLUDE_POSTGRESQL_TOOLS" in \
         true|yes|TRUE|YES) \
-            apk add --no-cache postgresql-client && \
+            apt-get install -y --no-install-recommends --no-install-suggests postgresql-client-17; \
             cd meshcentral && \
             echo -e "----------\nPREINSTALLING POSTGRESQL LIBRARIES...\n----------"; \
             npm install pg@8.14.1;; \
@@ -174,7 +202,7 @@ RUN case "$INCLUDE_POSTGRESQL_TOOLS" in \
 
 RUN case "$INCLUDE_MARIADB_TOOLS" in \
         true|yes|TRUE|YES) \
-            apk add --no-cache mariadb-client && \
+            apt-get install -y --no-install-recommends --no-install-suggests default-mysql-client mariadb-client; \
             cd meshcentral && \
             echo -e "----------\nPREINSTALLING MARIADB/MYSQL LIBRARIES...\n----------"; \
             npm install mariadb@3.4.0 mysql2@3.11.4;; \
@@ -185,9 +213,9 @@ RUN case "$INCLUDE_MARIADB_TOOLS" in \
             exit 1;; \
     esac
 
-# install dependencies from package.json
+# Remove left over files and cache
 RUN cd meshcentral \
-    && rm -rf /root/ /tmp/ /var/tmp/* /usr/lib/node_modules/npm/man /usr/lib/node_modules/npm/doc /usr/lib/node_modules/npm/html \
+    && rm -rf /root/* /tmp/* /var/tmp/* /usr/lib/node_modules/npm/man /usr/lib/node_modules/npm/doc /usr/lib/node_modules/npm/html \
     && npm cache clean --force
 
 # Expose needed ports
@@ -200,7 +228,7 @@ EXPOSE 80 443
 #VOLUME /opt/meshcentral/meshcentral-backups
 
 # Copy images from Git repo, place it before ending so recompilation can make good use of cache.
-COPY ./docker/entrypoint.sh ./entrypoint.sh
+COPY ./docker/entrypoint.sh /opt/meshcentral/entrypoint.sh
 COPY ./docker/config.json.template /opt/meshcentral/config.json.template
 
 ENTRYPOINT  ["bash", "/opt/meshcentral/entrypoint.sh"]
