feat: add debian-based docker image (#7414)
Signed-off-by: Simon Smith <simonsmith5521@gmail.com>
Signed-off-by: si458 <simonsmith5521@gmail.com>
Co-authored-by: Daan Selen <dselen@systemec.nl>
Co-authored-by: Simon Smith <simonsmith5521@gmail.com>
Co-authored-by: TheDevRyan <175502913+The-Dev-Ryan@users.noreply.github.com>

diff --git a/docker/Dockerfile-debian b/docker/Dockerfile-debian
--- a/docker/Dockerfile-debian
+++ b/docker/Dockerfile-debian
@@ -1,5 +1,5 @@
 ### STAGE 1 BUILDING.
-FROM node:22-alpine3.22 AS builder
+FROM node:22-trixie-slim AS builder
 
 # Any value inside one of the disable ARGs will be accepted.
 ARG DISABLE_EXTRACT="yes"
@@ -47,10 +47,13 @@ RUN rm -rf /opt/meshcentral/meshcentral/docker /opt/meshcentral/meshcentral/node
 
 ### STAGE 2 PRECOMPILE DEPS MODULE
 
-FROM node:22-alpine3.22 AS dep-compiler
+FROM node:22-trixie-slim AS dep-compiler
 
-RUN echo -e "----------\nINSTALLING ALPINE PACKAGES...\n----------"; \
-    apk add --no-cache --update \
+ENV NODE_ENV="production"
+
+RUN apt-get update && \
+    echo -e "----------\nINSTALLING DEBIAN PACKAGES...\n----------"; \
+    apt-get install -y --no-install-recommends --no-install-suggests \
         bash gcc g++ jq make python3 tzdata
 
 COPY --from=builder /opt/meshcentral/meshcentral /opt/meshcentral/meshcentral
@@ -61,13 +64,36 @@ RUN jq '.dependencies += {"modern-syslog": "1.2.0", "telegram": "2.26.22"}' pack
     && npm ci --omit=dev \
     && npm cache clean --force
 
-### STAGE 3 BUILDING.
+### STAGE 3 fun. building from source...
 
-FROM node:22-alpine3.22 AS finalizer
-#FROM alpine:3.22 AS finalizer
+FROM golang:trixie AS mongo-tools-compiler
 
-# copy files from previous layer
+ARG INCLUDE_MONGODB_TOOLS="false"
+
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends --no-install-suggests \
+        git lsb-release
+
+RUN case "$INCLUDE_MONGODB_TOOLS" in \
+        true|yes|TRUE|YES) \
+            git clone https://github.com/mongodb/mongo-tools /mongo-tools; \
+            cd /mongo-tools; \
+            ./make build -pkgs=mongodump,mongorestore;; \
+        false|no|FALSE|NO) \
+            echo "Not building MongoDB Tools from source, what a shame!"; \
+            mkdir -p /mongo-tools/bin;; \
+        *) \
+            echo "Invalid value for build argument INCLUDE_MONGODB_TOOLS, possible values: 'yes', 'true', 'no' or 'false'"; \
+            exit 1;; \
+    esac
+
+### STAGE 4 BUILDING.
+
+FROM node:22-trixie-slim AS finalizer
+
+# Copy files from previous layers
 COPY --from=dep-compiler /opt/meshcentral/meshcentral /opt/meshcentral/meshcentral
+COPY --from=mongo-tools-compiler /mongo-tools/bin/ /tmp/bin/
 
 # environment variables
 ENV NODE_ENV="production" \
@@ -116,25 +142,26 @@ ENV PSQL_HOST="" \
     PSQL_PASS="" \
     PSQL_DATABASE=""
 
-# MariaDB/MySQL Variables, Alpine Linux only provides the actual MariaDB binaries.
+# MariaDB/MySQL Variables.
 ENV MARIADB_HOST="" \
     MARIADB_PORT="3306" \
     MARIADB_USER="" \
     MARIADB_PASS="" \
     MARIADB_DATABASE=""
 
-RUN mkdir -p /opt/meshcentral/meshcentral
 WORKDIR /opt/meshcentral
 
-RUN echo -e "----------\nINSTALLING ALPINE PACKAGES...\n----------"; \
-    apk add --no-cache --update \
+RUN apt-get update && \
+    echo -e "----------\nINSTALLING DEBIAN PACKAGES...\n----------"; \
+    apt-get install -y --no-install-recommends --no-install-suggests \
         bash curl jq tzdata && \
-    rm -rf /var/cache/* \
-        /tmp/* \
+    rm -rf \
+        /var/cache/* \
         /usr/share/man/ \
         /usr/share/doc/ \
         /var/log/* \
         /var/spool/* \
+        /var/tmp/* \
         /usr/lib/debug/ && \
     npm install -g npm@latest
 
@@ -153,7 +180,7 @@ RUN case "$PREINSTALL_LIBS" in \
 # NOTE: ALL MODULES MUST HAVE A VERSION NUMBER AND THE VERSION MUST MATCH THAT USED IN meshcentraljs mainStart()
 RUN case "$INCLUDE_MONGODB_TOOLS" in \
         true|yes|TRUE|YES) \
-            apk add --no-cache mongodb-tools && \
+            mv /tmp/bin/* /usr/bin; \
             cd meshcentral && \
             echo -e "----------\nPREINSTALLING MONGODB LIBRARIES...\n----------"; \
             npm install mongodb@4.17.2 @mongodb-js/saslprep@1.3.1;; \
@@ -166,7 +193,7 @@ RUN case "$INCLUDE_MONGODB_TOOLS" in \
 
 RUN case "$INCLUDE_POSTGRESQL_TOOLS" in \
         true|yes|TRUE|YES) \
-            apk add --no-cache postgresql-client && \
+            apt-get install -y --no-install-recommends --no-install-suggests postgresql-client-17; \
             cd meshcentral && \
             echo -e "----------\nPREINSTALLING POSTGRESQL LIBRARIES...\n----------"; \
             npm install pg@8.14.1;; \
@@ -179,7 +206,7 @@ RUN case "$INCLUDE_POSTGRESQL_TOOLS" in \
 
 RUN case "$INCLUDE_MARIADB_TOOLS" in \
         true|yes|TRUE|YES) \
-            apk add --no-cache mariadb-client && \
+            apt-get install -y --no-install-recommends --no-install-suggests default-mysql-client mariadb-client; \
             cd meshcentral && \
             echo -e "----------\nPREINSTALLING MARIADB/MYSQL LIBRARIES...\n----------"; \
             npm install mariadb@3.4.0 mysql2@3.11.4;; \
